// GET /api/products/:slug
// Returns a single product by slug — hardcoded data until real DB is connected

import type { Product } from '~/types'

const PRODUCTS: Product[] = [
  {
    id: 1,
    slug: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    seoTitle: 'iPhone 16 Pro Max Chính Hãng - Hoàng Nam Phát',
    seoDescription: 'Mua iPhone 16 Pro Max chính hãng Apple tại Hoàng Nam Phát. Giá tốt, bảo hành 12 tháng, giao hàng toàn quốc.',
    thumbnail: '/images/products/iphone-16-pro-max.jpg',
    images: [
      '/images/products/iphone-16-pro-max-1.jpg',
      '/images/products/iphone-16-pro-max-2.jpg',
    ],
    price: 30000000,
    originalPrice: 33000000,
    sku: 'IP16PM',
    brand: 'Apple',
    category: 'Điện thoại',
    description: 'iPhone 16 Pro Max là đỉnh cao của dòng iPhone với chip A18 Pro mạnh mẽ nhất từ trước đến nay, màn hình Super Retina XDR ProMotion 6.9 inch sắc nét tuyệt đối, hệ thống camera chuyên nghiệp 48MP thế hệ mới với khả năng quay video 4K/120fps. Thiết kế titan cao cấp bền bỉ, pin cả ngày dài và tính năng Action Button linh hoạt. Nâng tầm trải nghiệm sáng tạo với Apple Intelligence.',
    specifications: [
      { label: 'Màn hình', value: '6.9 inch, Super Retina XDR, ProMotion 120Hz' },
      { label: 'Chip', value: 'Apple A18 Pro' },
      { label: 'Camera chính', value: '48MP Fusion, f/1.78, OIS' },
      { label: 'Camera telephoto', value: '12MP, 5x optical zoom' },
      { label: 'Camera trước', value: '12MP TrueDepth, f/1.9' },
      { label: 'RAM', value: '8GB' },
      { label: 'Bộ nhớ trong', value: '256GB / 512GB / 1TB' },
      { label: 'Pin', value: '4685 mAh, sạc 27W có dây, 25W MagSafe' },
      { label: 'Hệ điều hành', value: 'iOS 18' },
      { label: 'Kết nối', value: '5G, Wi-Fi 7, Bluetooth 5.3, NFC, USB-C 3.2' },
      { label: 'Chất liệu', value: 'Titanium Grade 5, kính cường lực Ceramic Shield' },
      { label: 'Kích thước', value: '163 x 77.6 x 8.25 mm' },
      { label: 'Trọng lượng', value: '228g' },
      { label: 'Màu sắc', value: 'Titan đen, Titan trắng, Titan tự nhiên, Titan sa mạc' },
      { label: 'Kháng nước', value: 'IP68 (6m / 30 phút)' },
    ],
    stock: 50,
    rating: 4.9,
    reviewCount: 128,
    isActive: true,
    createdAt: '2024-09-25',
    updatedAt: '2026-06-27',
  },
  {
    id: 2,
    slug: 'samsung-galaxy-s25-ultra',
    name: 'Samsung Galaxy S25 Ultra',
    seoTitle: 'Samsung Galaxy S25 Ultra Chính Hãng - Hoàng Nam Phát',
    seoDescription: 'Mua Samsung Galaxy S25 Ultra chính hãng tại Hoàng Nam Phát. Camera AI tiên tiến, pin bền bỉ.',
    thumbnail: '/images/products/galaxy-s25-ultra.jpg',
    images: ['/images/products/galaxy-s25-ultra-1.jpg'],
    price: 28000000,
    originalPrice: 30000000,
    sku: 'SGS25U',
    brand: 'Samsung',
    category: 'Điện thoại',
    description: 'Samsung Galaxy S25 Ultra là siêu phẩm Android với bút S Pen tích hợp thông minh, camera 200MP hàng đầu thị trường, chip Snapdragon 8 Elite hiệu năng vượt trội và pin 5000mAh siêu bền. Màn hình Dynamic AMOLED 2X 6.9 inch độ sáng 2600 nits cùng Galaxy AI thế hệ mới mang lại trải nghiệm AI toàn diện chưa từng có.',
    specifications: [
      { label: 'Màn hình', value: '6.9 inch, Dynamic AMOLED 2X, 120Hz, 2600 nits' },
      { label: 'Chip', value: 'Snapdragon 8 Elite for Galaxy' },
      { label: 'Camera chính', value: '200MP, f/1.7, OIS, PDAF' },
      { label: 'Camera telephoto', value: '50MP, 5x optical zoom + 10MP, 3x optical zoom' },
      { label: 'Camera trước', value: '12MP, f/2.2' },
      { label: 'RAM', value: '12GB' },
      { label: 'Bộ nhớ trong', value: '256GB / 512GB / 1TB' },
      { label: 'Pin', value: '5000 mAh, sạc 45W, không dây 15W' },
      { label: 'Hệ điều hành', value: 'Android 15, One UI 7' },
      { label: 'Kết nối', value: '5G, Wi-Fi 7, Bluetooth 5.4, NFC, USB-C 3.2' },
      { label: 'Bút S Pen', value: 'Tích hợp, độ trễ 2.8ms' },
      { label: 'Chất liệu', value: 'Titanium, Gorilla Glass Armor 2' },
      { label: 'Kích thước', value: '162.8 x 79 x 8.2 mm' },
      { label: 'Trọng lượng', value: '218g' },
      { label: 'Màu sắc', value: 'Titanium Silverblue, Titanium Black, Titanium Whitesilver' },
      { label: 'Kháng nước', value: 'IP68 (6m / 30 phút)' },
    ],
    stock: 35,
    rating: 4.8,
    reviewCount: 89,
    isActive: true,
    createdAt: '2025-01-22',
    updatedAt: '2026-06-27',
  },
  {
    id: 3,
    slug: 'macbook-pro-m4',
    name: 'MacBook Pro M4',
    seoTitle: 'MacBook Pro M4 Chính Hãng - Hoàng Nam Phát',
    seoDescription: 'Mua MacBook Pro M4 chính hãng Apple tại Hoàng Nam Phát. Hiệu năng vượt trội, màn hình Liquid Retina XDR.',
    thumbnail: '/images/products/macbook-pro-m4.jpg',
    images: ['/images/products/macbook-pro-m4-1.jpg'],
    price: 45000000,
    originalPrice: 48000000,
    sku: 'MBP-M4',
    brand: 'Apple',
    category: 'Laptop',
    description: 'MacBook Pro M4 mang đến hiệu năng chuyên nghiệp vượt trội với chip Apple M4 thế hệ mới, màn hình Liquid Retina XDR 14.2 inch tuyệt đẹp và thời lượng pin lên đến 24 giờ. Lý tưởng cho các nhà sáng tạo nội dung, lập trình viên và các chuyên gia cần máy tính mạnh mẽ, di động.',
    specifications: [
      { label: 'Màn hình', value: '14.2 inch, Liquid Retina XDR, 120Hz ProMotion, 1600 nits' },
      { label: 'Chip', value: 'Apple M4 (10-core CPU, 10-core GPU)' },
      { label: 'RAM', value: '16GB / 24GB / 32GB Unified Memory' },
      { label: 'Bộ nhớ trong', value: '512GB / 1TB / 2TB SSD' },
      { label: 'Camera', value: '12MP Center Stage' },
      { label: 'Pin', value: '72.4 Wh, lên đến 24 giờ' },
      { label: 'Hệ điều hành', value: 'macOS Sequoia' },
      { label: 'Kết nối', value: '3x Thunderbolt 4, HDMI 2.1, SD card, MagSafe 3, Wi-Fi 6E, Bluetooth 5.3' },
      { label: 'Âm thanh', value: '6 loa, âm thanh không gian Dolby Atmos' },
      { label: 'Bàn phím', value: 'Magic Keyboard Touch ID, Touch Bar' },
      { label: 'Kích thước', value: '312.6 x 221.2 x 15.5 mm' },
      { label: 'Trọng lượng', value: '1.55kg' },
      { label: 'Màu sắc', value: 'Space Black, Silver' },
    ],
    stock: 20,
    rating: 5.0,
    reviewCount: 45,
    isActive: true,
    createdAt: '2024-11-01',
    updatedAt: '2026-06-27',
  },
]

export default defineEventHandler((event) => {
  const slug = getRouterParam(event, 'slug')
  const product = PRODUCTS.find((p) => p.slug === slug)

  if (!product) {
    throw createError({ statusCode: 404, statusMessage: 'Product not found' })
  }

  return product
})
